/* File: cmprefmodule.c
 * This file is auto-generated with f2py (version:1.21.5).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Jun  8 18:28:40 2022
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *cmpref_error;
static PyObject *cmpref_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(cmpref_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define pyobj_from_complex_double1(v) (PyComplex_FromDoubles(v.r,v.i))
#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = cmpref_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = cmpref_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}

static int
complex_double_from_pyobj(complex_double* v, PyObject *obj, const char *errmess) {
    Py_complex c;
    if (PyComplex_Check(obj)) {
        c = PyComplex_AsCComplex(obj);
        (*v).r = c.real;
        (*v).i = c.imag;
        return 1;
    }
    if (PyArray_IsScalar(obj, ComplexFloating)) {
        if (PyArray_IsScalar(obj, CFloat)) {
            npy_cfloat new;
            PyArray_ScalarAsCtype(obj, &new);
            (*v).r = (double)new.real;
            (*v).i = (double)new.imag;
        }
        else if (PyArray_IsScalar(obj, CLongDouble)) {
            npy_clongdouble new;
            PyArray_ScalarAsCtype(obj, &new);
            (*v).r = (double)new.real;
            (*v).i = (double)new.imag;
        }
        else { /* if (PyArray_IsScalar(obj, CDouble)) */
            PyArray_ScalarAsCtype(obj, v);
        }
        return 1;
    }
    if (PyArray_CheckScalar(obj)) { /* 0-dim array or still array scalar */
        PyObject *arr;
        if (PyArray_Check(obj)) {
            arr = PyArray_Cast((PyArrayObject *)obj, NPY_CDOUBLE);
        }
        else {
            arr = PyArray_FromScalar(obj, PyArray_DescrFromType(NPY_CDOUBLE));
        }
        if (arr == NULL) {
            return 0;
        }
        (*v).r = ((npy_cdouble *)PyArray_DATA(arr))->real;
        (*v).i = ((npy_cdouble *)PyArray_DATA(arr))->imag;
        Py_DECREF(arr);
        return 1;
    }
    /* Python does not provide PyNumber_Complex function :-( */
    (*v).i = 0.0;
    if (PyFloat_Check(obj)) {
        (*v).r = PyFloat_AsDouble(obj);
        return !((*v).r == -1.0 && PyErr_Occurred());
    }
    if (PyLong_Check(obj)) {
        (*v).r = PyLong_AsDouble(obj);
        return !((*v).r == -1.0 && PyErr_Occurred());
    }
    if (PySequence_Check(obj) && !(PyBytes_Check(obj) || PyUnicode_Check(obj))) {
        PyObject *tmp = PySequence_GetItem(obj,0);
        if (tmp) {
            if (complex_double_from_pyobj(v,tmp,errmess)) {
                Py_DECREF(tmp);
                return 1;
            }
            Py_DECREF(tmp);
        }
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL)
            err = PyExc_TypeError;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int
string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess)
{
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyBytes_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyBytes_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyBytes_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = cmpref_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** calcrefl10cm ********************************/
static char doc_f2py_rout_cmpref_cmpref_mod_calcrefl10cm[] = "\
calcrefl10cm(qv,qc,qr,qs,qg,t,p,dBZ,[kte,ite,jte])\n\nWrapper for ``calcrefl10cm``.\
\n\nParameters\n----------\n"
"qv : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"qc : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"qr : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"qs : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"qg : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"t : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"p : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"dBZ : input rank-3 array('f') with bounds (kte,jte,ite)\n"
"\nOther Parameters\n----------------\n"
"kte : input int, optional\n    Default: shape(qv,0)\n"
"ite : input int, optional\n    Default: shape(qv,2)\n"
"jte : input int, optional\n    Default: shape(qv,1)";
/*  */
static PyObject *f2py_rout_cmpref_cmpref_mod_calcrefl10cm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float *qv = NULL;
  npy_intp qv_Dims[3] = {-1, -1, -1};
  const int qv_Rank = 3;
  PyArrayObject *capi_qv_tmp = NULL;
  int capi_qv_intent = 0;
  PyObject *qv_capi = Py_None;
  float *qc = NULL;
  npy_intp qc_Dims[3] = {-1, -1, -1};
  const int qc_Rank = 3;
  PyArrayObject *capi_qc_tmp = NULL;
  int capi_qc_intent = 0;
  PyObject *qc_capi = Py_None;
  float *qr = NULL;
  npy_intp qr_Dims[3] = {-1, -1, -1};
  const int qr_Rank = 3;
  PyArrayObject *capi_qr_tmp = NULL;
  int capi_qr_intent = 0;
  PyObject *qr_capi = Py_None;
  float *qs = NULL;
  npy_intp qs_Dims[3] = {-1, -1, -1};
  const int qs_Rank = 3;
  PyArrayObject *capi_qs_tmp = NULL;
  int capi_qs_intent = 0;
  PyObject *qs_capi = Py_None;
  float *qg = NULL;
  npy_intp qg_Dims[3] = {-1, -1, -1};
  const int qg_Rank = 3;
  PyArrayObject *capi_qg_tmp = NULL;
  int capi_qg_intent = 0;
  PyObject *qg_capi = Py_None;
  float *t = NULL;
  npy_intp t_Dims[3] = {-1, -1, -1};
  const int t_Rank = 3;
  PyArrayObject *capi_t_tmp = NULL;
  int capi_t_intent = 0;
  PyObject *t_capi = Py_None;
  float *p = NULL;
  npy_intp p_Dims[3] = {-1, -1, -1};
  const int p_Rank = 3;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  float *dBZ = NULL;
  npy_intp dBZ_Dims[3] = {-1, -1, -1};
  const int dBZ_Rank = 3;
  PyArrayObject *capi_dBZ_tmp = NULL;
  int capi_dBZ_intent = 0;
  PyObject *dBZ_capi = Py_None;
  int kte = 0;
  PyObject *kte_capi = Py_None;
  int ite = 0;
  PyObject *ite_capi = Py_None;
  int jte = 0;
  PyObject *jte_capi = Py_None;
    static char *capi_kwlist[] = {"qv","qc","qr","qs","qg","t","p","dBZ","kte","ite","jte",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|OOO:cmpref.cmpref_mod.calcrefl10cm",\
        capi_kwlist,&qv_capi,&qc_capi,&qr_capi,&qs_capi,&qg_capi,&t_capi,&p_capi,&dBZ_capi,&kte_capi,&ite_capi,&jte_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable qv */
  ;
  capi_qv_intent |= F2PY_INTENT_IN;
  capi_qv_tmp = array_from_pyobj(NPY_FLOAT,qv_Dims,qv_Rank,capi_qv_intent,qv_capi);
  if (capi_qv_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 1st argument `qv' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qv = (float *)(PyArray_DATA(capi_qv_tmp));

  /* Processing variable kte */
  if (kte_capi == Py_None) kte = shape(qv,0); else
    f2py_success = int_from_pyobj(&kte,kte_capi,"cmpref.cmpref_mod.calcrefl10cm() 1st keyword (kte) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(qv,0)==kte,"shape(qv,0)==kte","1st keyword kte","calcrefl10cm:kte=%d",kte) {
  /* Processing variable ite */
  if (ite_capi == Py_None) ite = shape(qv,2); else
    f2py_success = int_from_pyobj(&ite,ite_capi,"cmpref.cmpref_mod.calcrefl10cm() 2nd keyword (ite) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(qv,2)==ite,"shape(qv,2)==ite","2nd keyword ite","calcrefl10cm:ite=%d",ite) {
  /* Processing variable jte */
  if (jte_capi == Py_None) jte = shape(qv,1); else
    f2py_success = int_from_pyobj(&jte,jte_capi,"cmpref.cmpref_mod.calcrefl10cm() 3rd keyword (jte) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(qv,1)==jte,"shape(qv,1)==jte","3rd keyword jte","calcrefl10cm:jte=%d",jte) {
  /* Processing variable qc */
  qc_Dims[0]=kte,qc_Dims[1]=jte,qc_Dims[2]=ite;
  capi_qc_intent |= F2PY_INTENT_IN;
  capi_qc_tmp = array_from_pyobj(NPY_FLOAT,qc_Dims,qc_Rank,capi_qc_intent,qc_capi);
  if (capi_qc_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 2nd argument `qc' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qc = (float *)(PyArray_DATA(capi_qc_tmp));

  /* Processing variable qr */
  qr_Dims[0]=kte,qr_Dims[1]=jte,qr_Dims[2]=ite;
  capi_qr_intent |= F2PY_INTENT_IN;
  capi_qr_tmp = array_from_pyobj(NPY_FLOAT,qr_Dims,qr_Rank,capi_qr_intent,qr_capi);
  if (capi_qr_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 3rd argument `qr' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qr = (float *)(PyArray_DATA(capi_qr_tmp));

  /* Processing variable qs */
  qs_Dims[0]=kte,qs_Dims[1]=jte,qs_Dims[2]=ite;
  capi_qs_intent |= F2PY_INTENT_IN;
  capi_qs_tmp = array_from_pyobj(NPY_FLOAT,qs_Dims,qs_Rank,capi_qs_intent,qs_capi);
  if (capi_qs_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 4th argument `qs' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qs = (float *)(PyArray_DATA(capi_qs_tmp));

  /* Processing variable qg */
  qg_Dims[0]=kte,qg_Dims[1]=jte,qg_Dims[2]=ite;
  capi_qg_intent |= F2PY_INTENT_IN;
  capi_qg_tmp = array_from_pyobj(NPY_FLOAT,qg_Dims,qg_Rank,capi_qg_intent,qg_capi);
  if (capi_qg_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 5th argument `qg' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qg = (float *)(PyArray_DATA(capi_qg_tmp));

  /* Processing variable t */
  t_Dims[0]=kte,t_Dims[1]=jte,t_Dims[2]=ite;
  capi_t_intent |= F2PY_INTENT_IN;
  capi_t_tmp = array_from_pyobj(NPY_FLOAT,t_Dims,t_Rank,capi_t_intent,t_capi);
  if (capi_t_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 6th argument `t' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    t = (float *)(PyArray_DATA(capi_t_tmp));

  /* Processing variable p */
  p_Dims[0]=kte,p_Dims[1]=jte,p_Dims[2]=ite;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_FLOAT,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 7th argument `p' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p = (float *)(PyArray_DATA(capi_p_tmp));

  /* Processing variable dBZ */
  dBZ_Dims[0]=kte,dBZ_Dims[1]=jte,dBZ_Dims[2]=ite;
  capi_dBZ_intent |= F2PY_INTENT_IN;
  capi_dBZ_tmp = array_from_pyobj(NPY_FLOAT,dBZ_Dims,dBZ_Rank,capi_dBZ_intent,dBZ_capi);
  if (capi_dBZ_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 8th argument `dBZ' of cmpref.cmpref_mod.calcrefl10cm to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    dBZ = (float *)(PyArray_DATA(capi_dBZ_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(qv,qc,qr,qs,qg,t,p,dBZ,&kte,&ite,&jte);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_dBZ_tmp!=dBZ_capi) {
    Py_XDECREF(capi_dBZ_tmp); }
  }  /*if (capi_dBZ_tmp == NULL) ... else of dBZ*/
  /* End of cleaning variable dBZ */
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
  if((PyObject *)capi_t_tmp!=t_capi) {
    Py_XDECREF(capi_t_tmp); }
  }  /*if (capi_t_tmp == NULL) ... else of t*/
  /* End of cleaning variable t */
  if((PyObject *)capi_qg_tmp!=qg_capi) {
    Py_XDECREF(capi_qg_tmp); }
  }  /*if (capi_qg_tmp == NULL) ... else of qg*/
  /* End of cleaning variable qg */
  if((PyObject *)capi_qs_tmp!=qs_capi) {
    Py_XDECREF(capi_qs_tmp); }
  }  /*if (capi_qs_tmp == NULL) ... else of qs*/
  /* End of cleaning variable qs */
  if((PyObject *)capi_qr_tmp!=qr_capi) {
    Py_XDECREF(capi_qr_tmp); }
  }  /*if (capi_qr_tmp == NULL) ... else of qr*/
  /* End of cleaning variable qr */
  if((PyObject *)capi_qc_tmp!=qc_capi) {
    Py_XDECREF(capi_qc_tmp); }
  }  /*if (capi_qc_tmp == NULL) ... else of qc*/
  /* End of cleaning variable qc */
  } /*CHECKSCALAR(shape(qv,1)==jte)*/
  } /*if (f2py_success) of jte*/
  /* End of cleaning variable jte */
  } /*CHECKSCALAR(shape(qv,2)==ite)*/
  } /*if (f2py_success) of ite*/
  /* End of cleaning variable ite */
  } /*CHECKSCALAR(shape(qv,0)==kte)*/
  } /*if (f2py_success) of kte*/
  /* End of cleaning variable kte */
  if((PyObject *)capi_qv_tmp!=qv_capi) {
    Py_XDECREF(capi_qv_tmp); }
  }  /*if (capi_qv_tmp == NULL) ... else of qv*/
  /* End of cleaning variable qv */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of calcrefl10cm ****************************/

/******************************* calcrefl10cm1d *******************************/
static char doc_f2py_rout_cmpref_cmpref_mod_calcrefl10cm1d[] = "\
calcrefl10cm1d(qv1d,qc1d,qr1d,qs1d,qg1d,t1d,p1d,dBZ,rand1,kts,kte)\n\nWrapper for ``calcrefl10cm1d``.\
\n\nParameters\n----------\n"
"qv1d : input rank-1 array('f') with bounds (kte-kts+1)\n"
"qc1d : input rank-1 array('f') with bounds (kte-kts+1)\n"
"qr1d : input rank-1 array('f') with bounds (kte-kts+1)\n"
"qs1d : input rank-1 array('f') with bounds (kte-kts+1)\n"
"qg1d : input rank-1 array('f') with bounds (kte-kts+1)\n"
"t1d : input rank-1 array('f') with bounds (kte-kts+1)\n"
"p1d : input rank-1 array('f') with bounds (kte-kts+1)\n"
"dBZ : input rank-1 array('f') with bounds (kte-kts+1)\n"
"rand1 : input float\n"
"kts : input int\n"
"kte : input int";
/*  */
static PyObject *f2py_rout_cmpref_cmpref_mod_calcrefl10cm1d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*,float*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float *qv1d = NULL;
  npy_intp qv1d_Dims[1] = {-1};
  const int qv1d_Rank = 1;
  PyArrayObject *capi_qv1d_tmp = NULL;
  int capi_qv1d_intent = 0;
  PyObject *qv1d_capi = Py_None;
  float *qc1d = NULL;
  npy_intp qc1d_Dims[1] = {-1};
  const int qc1d_Rank = 1;
  PyArrayObject *capi_qc1d_tmp = NULL;
  int capi_qc1d_intent = 0;
  PyObject *qc1d_capi = Py_None;
  float *qr1d = NULL;
  npy_intp qr1d_Dims[1] = {-1};
  const int qr1d_Rank = 1;
  PyArrayObject *capi_qr1d_tmp = NULL;
  int capi_qr1d_intent = 0;
  PyObject *qr1d_capi = Py_None;
  float *qs1d = NULL;
  npy_intp qs1d_Dims[1] = {-1};
  const int qs1d_Rank = 1;
  PyArrayObject *capi_qs1d_tmp = NULL;
  int capi_qs1d_intent = 0;
  PyObject *qs1d_capi = Py_None;
  float *qg1d = NULL;
  npy_intp qg1d_Dims[1] = {-1};
  const int qg1d_Rank = 1;
  PyArrayObject *capi_qg1d_tmp = NULL;
  int capi_qg1d_intent = 0;
  PyObject *qg1d_capi = Py_None;
  float *t1d = NULL;
  npy_intp t1d_Dims[1] = {-1};
  const int t1d_Rank = 1;
  PyArrayObject *capi_t1d_tmp = NULL;
  int capi_t1d_intent = 0;
  PyObject *t1d_capi = Py_None;
  float *p1d = NULL;
  npy_intp p1d_Dims[1] = {-1};
  const int p1d_Rank = 1;
  PyArrayObject *capi_p1d_tmp = NULL;
  int capi_p1d_intent = 0;
  PyObject *p1d_capi = Py_None;
  float *dBZ = NULL;
  npy_intp dBZ_Dims[1] = {-1};
  const int dBZ_Rank = 1;
  PyArrayObject *capi_dBZ_tmp = NULL;
  int capi_dBZ_intent = 0;
  PyObject *dBZ_capi = Py_None;
  float rand1 = 0;
  PyObject *rand1_capi = Py_None;
  int kts = 0;
  PyObject *kts_capi = Py_None;
  int kte = 0;
  PyObject *kte_capi = Py_None;
    static char *capi_kwlist[] = {"qv1d","qc1d","qr1d","qs1d","qg1d","t1d","p1d","dBZ","rand1","kts","kte",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOO|:cmpref.cmpref_mod.calcrefl10cm1d",\
        capi_kwlist,&qv1d_capi,&qc1d_capi,&qr1d_capi,&qs1d_capi,&qg1d_capi,&t1d_capi,&p1d_capi,&dBZ_capi,&rand1_capi,&kts_capi,&kte_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable kts */
    f2py_success = int_from_pyobj(&kts,kts_capi,"cmpref.cmpref_mod.calcrefl10cm1d() 10th argument (kts) can't be converted to int");
  if (f2py_success) {
  /* Processing variable kte */
    f2py_success = int_from_pyobj(&kte,kte_capi,"cmpref.cmpref_mod.calcrefl10cm1d() 11st argument (kte) can't be converted to int");
  if (f2py_success) {
  /* Processing variable rand1 */
    f2py_success = float_from_pyobj(&rand1,rand1_capi,"cmpref.cmpref_mod.calcrefl10cm1d() 9th argument (rand1) can't be converted to float");
  if (f2py_success) {
  /* Processing variable qv1d */
  qv1d_Dims[0]=kte-kts+1;
  capi_qv1d_intent |= F2PY_INTENT_IN;
  capi_qv1d_tmp = array_from_pyobj(NPY_FLOAT,qv1d_Dims,qv1d_Rank,capi_qv1d_intent,qv1d_capi);
  if (capi_qv1d_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 1st argument `qv1d' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qv1d = (float *)(PyArray_DATA(capi_qv1d_tmp));

  /* Processing variable qc1d */
  qc1d_Dims[0]=kte-kts+1;
  capi_qc1d_intent |= F2PY_INTENT_IN;
  capi_qc1d_tmp = array_from_pyobj(NPY_FLOAT,qc1d_Dims,qc1d_Rank,capi_qc1d_intent,qc1d_capi);
  if (capi_qc1d_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 2nd argument `qc1d' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qc1d = (float *)(PyArray_DATA(capi_qc1d_tmp));

  /* Processing variable qr1d */
  qr1d_Dims[0]=kte-kts+1;
  capi_qr1d_intent |= F2PY_INTENT_IN;
  capi_qr1d_tmp = array_from_pyobj(NPY_FLOAT,qr1d_Dims,qr1d_Rank,capi_qr1d_intent,qr1d_capi);
  if (capi_qr1d_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 3rd argument `qr1d' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qr1d = (float *)(PyArray_DATA(capi_qr1d_tmp));

  /* Processing variable qs1d */
  qs1d_Dims[0]=kte-kts+1;
  capi_qs1d_intent |= F2PY_INTENT_IN;
  capi_qs1d_tmp = array_from_pyobj(NPY_FLOAT,qs1d_Dims,qs1d_Rank,capi_qs1d_intent,qs1d_capi);
  if (capi_qs1d_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 4th argument `qs1d' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qs1d = (float *)(PyArray_DATA(capi_qs1d_tmp));

  /* Processing variable qg1d */
  qg1d_Dims[0]=kte-kts+1;
  capi_qg1d_intent |= F2PY_INTENT_IN;
  capi_qg1d_tmp = array_from_pyobj(NPY_FLOAT,qg1d_Dims,qg1d_Rank,capi_qg1d_intent,qg1d_capi);
  if (capi_qg1d_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 5th argument `qg1d' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    qg1d = (float *)(PyArray_DATA(capi_qg1d_tmp));

  /* Processing variable t1d */
  t1d_Dims[0]=kte-kts+1;
  capi_t1d_intent |= F2PY_INTENT_IN;
  capi_t1d_tmp = array_from_pyobj(NPY_FLOAT,t1d_Dims,t1d_Rank,capi_t1d_intent,t1d_capi);
  if (capi_t1d_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 6th argument `t1d' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    t1d = (float *)(PyArray_DATA(capi_t1d_tmp));

  /* Processing variable p1d */
  p1d_Dims[0]=kte-kts+1;
  capi_p1d_intent |= F2PY_INTENT_IN;
  capi_p1d_tmp = array_from_pyobj(NPY_FLOAT,p1d_Dims,p1d_Rank,capi_p1d_intent,p1d_capi);
  if (capi_p1d_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 7th argument `p1d' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    p1d = (float *)(PyArray_DATA(capi_p1d_tmp));

  /* Processing variable dBZ */
  dBZ_Dims[0]=kte-kts+1;
  capi_dBZ_intent |= F2PY_INTENT_IN;
  capi_dBZ_tmp = array_from_pyobj(NPY_FLOAT,dBZ_Dims,dBZ_Rank,capi_dBZ_intent,dBZ_capi);
  if (capi_dBZ_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : cmpref_error,"failed in converting 8th argument `dBZ' of cmpref.cmpref_mod.calcrefl10cm1d to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    dBZ = (float *)(PyArray_DATA(capi_dBZ_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(qv1d,qc1d,qr1d,qs1d,qg1d,t1d,p1d,dBZ,&rand1,&kts,&kte);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_dBZ_tmp!=dBZ_capi) {
    Py_XDECREF(capi_dBZ_tmp); }
  }  /*if (capi_dBZ_tmp == NULL) ... else of dBZ*/
  /* End of cleaning variable dBZ */
  if((PyObject *)capi_p1d_tmp!=p1d_capi) {
    Py_XDECREF(capi_p1d_tmp); }
  }  /*if (capi_p1d_tmp == NULL) ... else of p1d*/
  /* End of cleaning variable p1d */
  if((PyObject *)capi_t1d_tmp!=t1d_capi) {
    Py_XDECREF(capi_t1d_tmp); }
  }  /*if (capi_t1d_tmp == NULL) ... else of t1d*/
  /* End of cleaning variable t1d */
  if((PyObject *)capi_qg1d_tmp!=qg1d_capi) {
    Py_XDECREF(capi_qg1d_tmp); }
  }  /*if (capi_qg1d_tmp == NULL) ... else of qg1d*/
  /* End of cleaning variable qg1d */
  if((PyObject *)capi_qs1d_tmp!=qs1d_capi) {
    Py_XDECREF(capi_qs1d_tmp); }
  }  /*if (capi_qs1d_tmp == NULL) ... else of qs1d*/
  /* End of cleaning variable qs1d */
  if((PyObject *)capi_qr1d_tmp!=qr1d_capi) {
    Py_XDECREF(capi_qr1d_tmp); }
  }  /*if (capi_qr1d_tmp == NULL) ... else of qr1d*/
  /* End of cleaning variable qr1d */
  if((PyObject *)capi_qc1d_tmp!=qc1d_capi) {
    Py_XDECREF(capi_qc1d_tmp); }
  }  /*if (capi_qc1d_tmp == NULL) ... else of qc1d*/
  /* End of cleaning variable qc1d */
  if((PyObject *)capi_qv1d_tmp!=qv1d_capi) {
    Py_XDECREF(capi_qv1d_tmp); }
  }  /*if (capi_qv1d_tmp == NULL) ... else of qv1d*/
  /* End of cleaning variable qv1d */
  } /*if (f2py_success) of rand1*/
  /* End of cleaning variable rand1 */
  } /*if (f2py_success) of kte*/
  /* End of cleaning variable kte */
  } /*if (f2py_success) of kts*/
  /* End of cleaning variable kts */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of calcrefl10cm1d ***************************/

/*************************** rayleighsoakwetgraupel ***************************/
static char doc_f2py_rout_cmpref_cmpref_mod_rayleighsoakwetgraupel[] = "\
Cback = rayleighsoakwetgraupel(xg,ageo,bgeo,fmelt,meltratiooutside,mw,mi,lambda,mixingrule,matrix,inclusion,host,hostmatrix,hostinclusion)\n\nWrapper for ``rayleighsoakwetgraupel``.\
\n\nParameters\n----------\n"
"xg : input float\n"
"ageo : input float\n"
"bgeo : input float\n"
"fmelt : input float\n"
"meltratiooutside : input float\n"
"mw : input complex\n"
"mi : input complex\n"
"lambda : input float\n"
"mixingrule : input string(len=-1)\n"
"matrix : input string(len=-1)\n"
"inclusion : input string(len=-1)\n"
"host : input string(len=-1)\n"
"hostmatrix : input string(len=-1)\n"
"hostinclusion : input string(len=-1)\n"
"\nReturns\n-------\n"
"Cback : float";
/*  */
static PyObject *f2py_rout_cmpref_cmpref_mod_rayleighsoakwetgraupel(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,complex_double*,complex_double*,double*,double*,string,string,string,string,string,string,size_t,size_t,size_t,size_t,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  double xg = 0;
  PyObject *xg_capi = Py_None;
  double ageo = 0;
  PyObject *ageo_capi = Py_None;
  double bgeo = 0;
  PyObject *bgeo_capi = Py_None;
  double fmelt = 0;
  PyObject *fmelt_capi = Py_None;
  double meltratiooutside = 0;
  PyObject *meltratiooutside_capi = Py_None;
  complex_double mw;
  PyObject *mw_capi = Py_None;
  complex_double mi;
  PyObject *mi_capi = Py_None;
  double lambda = 0;
  PyObject *lambda_capi = Py_None;
  double Cback = 0;
  string mixingrule = NULL;
  int slen(mixingrule);
  PyObject *mixingrule_capi = Py_None;
  string matrix = NULL;
  int slen(matrix);
  PyObject *matrix_capi = Py_None;
  string inclusion = NULL;
  int slen(inclusion);
  PyObject *inclusion_capi = Py_None;
  string host = NULL;
  int slen(host);
  PyObject *host_capi = Py_None;
  string hostmatrix = NULL;
  int slen(hostmatrix);
  PyObject *hostmatrix_capi = Py_None;
  string hostinclusion = NULL;
  int slen(hostinclusion);
  PyObject *hostinclusion_capi = Py_None;
    static char *capi_kwlist[] = {"xg","ageo","bgeo","fmelt","meltratiooutside","mw","mi","lambda","mixingrule","matrix","inclusion","host","hostmatrix","hostinclusion",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOO|:cmpref.cmpref_mod.rayleighsoakwetgraupel",\
        capi_kwlist,&xg_capi,&ageo_capi,&bgeo_capi,&fmelt_capi,&meltratiooutside_capi,&mw_capi,&mi_capi,&lambda_capi,&mixingrule_capi,&matrix_capi,&inclusion_capi,&host_capi,&hostmatrix_capi,&hostinclusion_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable xg */
    f2py_success = double_from_pyobj(&xg,xg_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 1st argument (xg) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ageo */
    f2py_success = double_from_pyobj(&ageo,ageo_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 2nd argument (ageo) can't be converted to double");
  if (f2py_success) {
  /* Processing variable bgeo */
    f2py_success = double_from_pyobj(&bgeo,bgeo_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 3rd argument (bgeo) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fmelt */
    f2py_success = double_from_pyobj(&fmelt,fmelt_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 4th argument (fmelt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable lambda */
    f2py_success = double_from_pyobj(&lambda,lambda_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 8th argument (lambda) can't be converted to double");
  if (f2py_success) {
  /* Processing variable meltratiooutside */
    f2py_success = double_from_pyobj(&meltratiooutside,meltratiooutside_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 5th argument (meltratiooutside) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Cback */
  /* Processing variable mw */
    f2py_success = complex_double_from_pyobj(&mw,mw_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 6th argument (mw) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mi */
    f2py_success = complex_double_from_pyobj(&mi,mi_capi,"cmpref.cmpref_mod.rayleighsoakwetgraupel() 7th argument (mi) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mixingrule */
  slen(mixingrule) = -1;
  f2py_success = string_from_pyobj(&mixingrule,&slen(mixingrule),"",mixingrule_capi,"string_from_pyobj failed in converting 9th argument `mixingrule' of cmpref.cmpref_mod.rayleighsoakwetgraupel to C string");
  if (f2py_success) {
  /* Processing variable matrix */
  slen(matrix) = -1;
  f2py_success = string_from_pyobj(&matrix,&slen(matrix),"",matrix_capi,"string_from_pyobj failed in converting 10th argument `matrix' of cmpref.cmpref_mod.rayleighsoakwetgraupel to C string");
  if (f2py_success) {
  /* Processing variable inclusion */
  slen(inclusion) = -1;
  f2py_success = string_from_pyobj(&inclusion,&slen(inclusion),"",inclusion_capi,"string_from_pyobj failed in converting 11st argument `inclusion' of cmpref.cmpref_mod.rayleighsoakwetgraupel to C string");
  if (f2py_success) {
  /* Processing variable host */
  slen(host) = -1;
  f2py_success = string_from_pyobj(&host,&slen(host),"",host_capi,"string_from_pyobj failed in converting 12nd argument `host' of cmpref.cmpref_mod.rayleighsoakwetgraupel to C string");
  if (f2py_success) {
  /* Processing variable hostmatrix */
  slen(hostmatrix) = -1;
  f2py_success = string_from_pyobj(&hostmatrix,&slen(hostmatrix),"",hostmatrix_capi,"string_from_pyobj failed in converting 13rd argument `hostmatrix' of cmpref.cmpref_mod.rayleighsoakwetgraupel to C string");
  if (f2py_success) {
  /* Processing variable hostinclusion */
  slen(hostinclusion) = -1;
  f2py_success = string_from_pyobj(&hostinclusion,&slen(hostinclusion),"",hostinclusion_capi,"string_from_pyobj failed in converting 14th argument `hostinclusion' of cmpref.cmpref_mod.rayleighsoakwetgraupel to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&xg,&ageo,&bgeo,&fmelt,&meltratiooutside,&mw,&mi,&lambda,&Cback,mixingrule,matrix,inclusion,host,hostmatrix,hostinclusion,slen(mixingrule),slen(matrix),slen(inclusion),slen(host),slen(hostmatrix),slen(hostinclusion));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",Cback);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(hostinclusion);
  }  /*if (f2py_success) of hostinclusion*/
  /* End of cleaning variable hostinclusion */
    STRINGFREE(hostmatrix);
  }  /*if (f2py_success) of hostmatrix*/
  /* End of cleaning variable hostmatrix */
    STRINGFREE(host);
  }  /*if (f2py_success) of host*/
  /* End of cleaning variable host */
    STRINGFREE(inclusion);
  }  /*if (f2py_success) of inclusion*/
  /* End of cleaning variable inclusion */
    STRINGFREE(matrix);
  }  /*if (f2py_success) of matrix*/
  /* End of cleaning variable matrix */
    STRINGFREE(mixingrule);
  }  /*if (f2py_success) of mixingrule*/
  /* End of cleaning variable mixingrule */
  }  /*if (f2py_success) of mi frompyobj*/
  /* End of cleaning variable mi */
  }  /*if (f2py_success) of mw frompyobj*/
  /* End of cleaning variable mw */
  /* End of cleaning variable Cback */
  } /*if (f2py_success) of meltratiooutside*/
  /* End of cleaning variable meltratiooutside */
  } /*if (f2py_success) of lambda*/
  /* End of cleaning variable lambda */
  } /*if (f2py_success) of fmelt*/
  /* End of cleaning variable fmelt */
  } /*if (f2py_success) of bgeo*/
  /* End of cleaning variable bgeo */
  } /*if (f2py_success) of ageo*/
  /* End of cleaning variable ageo */
  } /*if (f2py_success) of xg*/
  /* End of cleaning variable xg */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********************** end of rayleighsoakwetgraupel ***********************/

/****************************** get_m_mix_nested ******************************/
static char doc_f2py_rout_cmpref_cmpref_mod_get_m_mix_nested[] = "\
cumulerror = get_m_mix_nested(mmixn,ma,mi,mw,volair,volice,volwater,mixingrule,host,matrix,inclusion,hostmatrix,hostinclusion)\n\nWrapper for ``get_m_mix_nested``.\
\n\nParameters\n----------\n"
"mmixn : input complex\n"
"ma : input complex\n"
"mi : input complex\n"
"mw : input complex\n"
"volair : input float\n"
"volice : input float\n"
"volwater : input float\n"
"mixingrule : input string(len=-1)\n"
"host : input string(len=-1)\n"
"matrix : input string(len=-1)\n"
"inclusion : input string(len=-1)\n"
"hostmatrix : input string(len=-1)\n"
"hostinclusion : input string(len=-1)\n"
"\nReturns\n-------\n"
"cumulerror : int";
/*  */
static PyObject *f2py_rout_cmpref_cmpref_mod_get_m_mix_nested(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_double*,complex_double*,complex_double*,complex_double*,double*,double*,double*,string,string,string,string,string,string,int*,size_t,size_t,size_t,size_t,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  complex_double mmixn;
  PyObject *mmixn_capi = Py_None;
  complex_double ma;
  PyObject *ma_capi = Py_None;
  complex_double mi;
  PyObject *mi_capi = Py_None;
  complex_double mw;
  PyObject *mw_capi = Py_None;
  double volair = 0;
  PyObject *volair_capi = Py_None;
  double volice = 0;
  PyObject *volice_capi = Py_None;
  double volwater = 0;
  PyObject *volwater_capi = Py_None;
  string mixingrule = NULL;
  int slen(mixingrule);
  PyObject *mixingrule_capi = Py_None;
  string host = NULL;
  int slen(host);
  PyObject *host_capi = Py_None;
  string matrix = NULL;
  int slen(matrix);
  PyObject *matrix_capi = Py_None;
  string inclusion = NULL;
  int slen(inclusion);
  PyObject *inclusion_capi = Py_None;
  string hostmatrix = NULL;
  int slen(hostmatrix);
  PyObject *hostmatrix_capi = Py_None;
  string hostinclusion = NULL;
  int slen(hostinclusion);
  PyObject *hostinclusion_capi = Py_None;
  int cumulerror = 0;
    static char *capi_kwlist[] = {"mmixn","ma","mi","mw","volair","volice","volwater","mixingrule","host","matrix","inclusion","hostmatrix","hostinclusion",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOO|:cmpref.cmpref_mod.get_m_mix_nested",\
        capi_kwlist,&mmixn_capi,&ma_capi,&mi_capi,&mw_capi,&volair_capi,&volice_capi,&volwater_capi,&mixingrule_capi,&host_capi,&matrix_capi,&inclusion_capi,&hostmatrix_capi,&hostinclusion_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable mmixn */
    f2py_success = complex_double_from_pyobj(&mmixn,mmixn_capi,"cmpref.cmpref_mod.get_m_mix_nested() 1st argument (mmixn) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable volice */
    f2py_success = double_from_pyobj(&volice,volice_capi,"cmpref.cmpref_mod.get_m_mix_nested() 6th argument (volice) can't be converted to double");
  if (f2py_success) {
  /* Processing variable volair */
    f2py_success = double_from_pyobj(&volair,volair_capi,"cmpref.cmpref_mod.get_m_mix_nested() 5th argument (volair) can't be converted to double");
  if (f2py_success) {
  /* Processing variable volwater */
    f2py_success = double_from_pyobj(&volwater,volwater_capi,"cmpref.cmpref_mod.get_m_mix_nested() 7th argument (volwater) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ma */
    f2py_success = complex_double_from_pyobj(&ma,ma_capi,"cmpref.cmpref_mod.get_m_mix_nested() 2nd argument (ma) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mi */
    f2py_success = complex_double_from_pyobj(&mi,mi_capi,"cmpref.cmpref_mod.get_m_mix_nested() 3rd argument (mi) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mw */
    f2py_success = complex_double_from_pyobj(&mw,mw_capi,"cmpref.cmpref_mod.get_m_mix_nested() 4th argument (mw) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mixingrule */
  slen(mixingrule) = -1;
  f2py_success = string_from_pyobj(&mixingrule,&slen(mixingrule),"",mixingrule_capi,"string_from_pyobj failed in converting 8th argument `mixingrule' of cmpref.cmpref_mod.get_m_mix_nested to C string");
  if (f2py_success) {
  /* Processing variable host */
  slen(host) = -1;
  f2py_success = string_from_pyobj(&host,&slen(host),"",host_capi,"string_from_pyobj failed in converting 9th argument `host' of cmpref.cmpref_mod.get_m_mix_nested to C string");
  if (f2py_success) {
  /* Processing variable matrix */
  slen(matrix) = -1;
  f2py_success = string_from_pyobj(&matrix,&slen(matrix),"",matrix_capi,"string_from_pyobj failed in converting 10th argument `matrix' of cmpref.cmpref_mod.get_m_mix_nested to C string");
  if (f2py_success) {
  /* Processing variable inclusion */
  slen(inclusion) = -1;
  f2py_success = string_from_pyobj(&inclusion,&slen(inclusion),"",inclusion_capi,"string_from_pyobj failed in converting 11st argument `inclusion' of cmpref.cmpref_mod.get_m_mix_nested to C string");
  if (f2py_success) {
  /* Processing variable hostmatrix */
  slen(hostmatrix) = -1;
  f2py_success = string_from_pyobj(&hostmatrix,&slen(hostmatrix),"",hostmatrix_capi,"string_from_pyobj failed in converting 12nd argument `hostmatrix' of cmpref.cmpref_mod.get_m_mix_nested to C string");
  if (f2py_success) {
  /* Processing variable hostinclusion */
  slen(hostinclusion) = -1;
  f2py_success = string_from_pyobj(&hostinclusion,&slen(hostinclusion),"",hostinclusion_capi,"string_from_pyobj failed in converting 13rd argument `hostinclusion' of cmpref.cmpref_mod.get_m_mix_nested to C string");
  if (f2py_success) {
  /* Processing variable cumulerror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&mmixn,&ma,&mi,&mw,&volair,&volice,&volwater,mixingrule,host,matrix,inclusion,hostmatrix,hostinclusion,&cumulerror,slen(mixingrule),slen(host),slen(matrix),slen(inclusion),slen(hostmatrix),slen(hostinclusion));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",cumulerror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable cumulerror */
    STRINGFREE(hostinclusion);
  }  /*if (f2py_success) of hostinclusion*/
  /* End of cleaning variable hostinclusion */
    STRINGFREE(hostmatrix);
  }  /*if (f2py_success) of hostmatrix*/
  /* End of cleaning variable hostmatrix */
    STRINGFREE(inclusion);
  }  /*if (f2py_success) of inclusion*/
  /* End of cleaning variable inclusion */
    STRINGFREE(matrix);
  }  /*if (f2py_success) of matrix*/
  /* End of cleaning variable matrix */
    STRINGFREE(host);
  }  /*if (f2py_success) of host*/
  /* End of cleaning variable host */
    STRINGFREE(mixingrule);
  }  /*if (f2py_success) of mixingrule*/
  /* End of cleaning variable mixingrule */
  }  /*if (f2py_success) of mw frompyobj*/
  /* End of cleaning variable mw */
  }  /*if (f2py_success) of mi frompyobj*/
  /* End of cleaning variable mi */
  }  /*if (f2py_success) of ma frompyobj*/
  /* End of cleaning variable ma */
  } /*if (f2py_success) of volwater*/
  /* End of cleaning variable volwater */
  } /*if (f2py_success) of volair*/
  /* End of cleaning variable volair */
  } /*if (f2py_success) of volice*/
  /* End of cleaning variable volice */
  }  /*if (f2py_success) of mmixn frompyobj*/
  /* End of cleaning variable mmixn */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of get_m_mix_nested **************************/

/********************************* get_m_mix *********************************/
static char doc_f2py_rout_cmpref_cmpref_mod_get_m_mix[] = "\
error = get_m_mix(mmix,ma,mi,mw,volair,volice,volwater,mixingrule,matrix,inclusion)\n\nWrapper for ``get_m_mix``.\
\n\nParameters\n----------\n"
"mmix : input complex\n"
"ma : input complex\n"
"mi : input complex\n"
"mw : input complex\n"
"volair : input float\n"
"volice : input float\n"
"volwater : input float\n"
"mixingrule : input string(len=-1)\n"
"matrix : input string(len=-1)\n"
"inclusion : input string(len=-1)\n"
"\nReturns\n-------\n"
"error : int";
/*  */
static PyObject *f2py_rout_cmpref_cmpref_mod_get_m_mix(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_double*,complex_double*,complex_double*,complex_double*,double*,double*,double*,string,string,string,int*,size_t,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  complex_double mmix;
  PyObject *mmix_capi = Py_None;
  complex_double ma;
  PyObject *ma_capi = Py_None;
  complex_double mi;
  PyObject *mi_capi = Py_None;
  complex_double mw;
  PyObject *mw_capi = Py_None;
  double volair = 0;
  PyObject *volair_capi = Py_None;
  double volice = 0;
  PyObject *volice_capi = Py_None;
  double volwater = 0;
  PyObject *volwater_capi = Py_None;
  string mixingrule = NULL;
  int slen(mixingrule);
  PyObject *mixingrule_capi = Py_None;
  string matrix = NULL;
  int slen(matrix);
  PyObject *matrix_capi = Py_None;
  string inclusion = NULL;
  int slen(inclusion);
  PyObject *inclusion_capi = Py_None;
  int error = 0;
    static char *capi_kwlist[] = {"mmix","ma","mi","mw","volair","volice","volwater","mixingrule","matrix","inclusion",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOO|:cmpref.cmpref_mod.get_m_mix",\
        capi_kwlist,&mmix_capi,&ma_capi,&mi_capi,&mw_capi,&volair_capi,&volice_capi,&volwater_capi,&mixingrule_capi,&matrix_capi,&inclusion_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable volice */
    f2py_success = double_from_pyobj(&volice,volice_capi,"cmpref.cmpref_mod.get_m_mix() 6th argument (volice) can't be converted to double");
  if (f2py_success) {
  /* Processing variable volair */
    f2py_success = double_from_pyobj(&volair,volair_capi,"cmpref.cmpref_mod.get_m_mix() 5th argument (volair) can't be converted to double");
  if (f2py_success) {
  /* Processing variable volwater */
    f2py_success = double_from_pyobj(&volwater,volwater_capi,"cmpref.cmpref_mod.get_m_mix() 7th argument (volwater) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ma */
    f2py_success = complex_double_from_pyobj(&ma,ma_capi,"cmpref.cmpref_mod.get_m_mix() 2nd argument (ma) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mi */
    f2py_success = complex_double_from_pyobj(&mi,mi_capi,"cmpref.cmpref_mod.get_m_mix() 3rd argument (mi) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mw */
    f2py_success = complex_double_from_pyobj(&mw,mw_capi,"cmpref.cmpref_mod.get_m_mix() 4th argument (mw) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable mixingrule */
  slen(mixingrule) = -1;
  f2py_success = string_from_pyobj(&mixingrule,&slen(mixingrule),"",mixingrule_capi,"string_from_pyobj failed in converting 8th argument `mixingrule' of cmpref.cmpref_mod.get_m_mix to C string");
  if (f2py_success) {
  /* Processing variable matrix */
  slen(matrix) = -1;
  f2py_success = string_from_pyobj(&matrix,&slen(matrix),"",matrix_capi,"string_from_pyobj failed in converting 9th argument `matrix' of cmpref.cmpref_mod.get_m_mix to C string");
  if (f2py_success) {
  /* Processing variable inclusion */
  slen(inclusion) = -1;
  f2py_success = string_from_pyobj(&inclusion,&slen(inclusion),"",inclusion_capi,"string_from_pyobj failed in converting 10th argument `inclusion' of cmpref.cmpref_mod.get_m_mix to C string");
  if (f2py_success) {
  /* Processing variable error */
  /* Processing variable mmix */
    f2py_success = complex_double_from_pyobj(&mmix,mmix_capi,"cmpref.cmpref_mod.get_m_mix() 1st argument (mmix) can't be converted to complex_double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&mmix,&ma,&mi,&mw,&volair,&volice,&volwater,mixingrule,matrix,inclusion,&error,slen(mixingrule),slen(matrix),slen(inclusion));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",error);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (f2py_success) of mmix frompyobj*/
  /* End of cleaning variable mmix */
  /* End of cleaning variable error */
    STRINGFREE(inclusion);
  }  /*if (f2py_success) of inclusion*/
  /* End of cleaning variable inclusion */
    STRINGFREE(matrix);
  }  /*if (f2py_success) of matrix*/
  /* End of cleaning variable matrix */
    STRINGFREE(mixingrule);
  }  /*if (f2py_success) of mixingrule*/
  /* End of cleaning variable mixingrule */
  }  /*if (f2py_success) of mw frompyobj*/
  /* End of cleaning variable mw */
  }  /*if (f2py_success) of mi frompyobj*/
  /* End of cleaning variable mi */
  }  /*if (f2py_success) of ma frompyobj*/
  /* End of cleaning variable ma */
  } /*if (f2py_success) of volwater*/
  /* End of cleaning variable volwater */
  } /*if (f2py_success) of volair*/
  /* End of cleaning variable volair */
  } /*if (f2py_success) of volice*/
  /* End of cleaning variable volice */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of get_m_mix ******************************/

/*************************** mcomplexmaxwellgarnett ***************************/
static char doc_f2py_rout_cmpref_cmpref_mod_mcomplexmaxwellgarnett[] = "\
error = mcomplexmaxwellgarnett(mmg,vol1,vol2,vol3,m1,m2,m3,inclusion)\n\nWrapper for ``mcomplexmaxwellgarnett``.\
\n\nParameters\n----------\n"
"mmg : input complex\n"
"vol1 : input float\n"
"vol2 : input float\n"
"vol3 : input float\n"
"m1 : input complex\n"
"m2 : input complex\n"
"m3 : input complex\n"
"inclusion : input string(len=-1)\n"
"\nReturns\n-------\n"
"error : int";
/*  */
static PyObject *f2py_rout_cmpref_cmpref_mod_mcomplexmaxwellgarnett(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_double*,double*,double*,double*,complex_double*,complex_double*,complex_double*,string,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  complex_double mmg;
  PyObject *mmg_capi = Py_None;
  double vol1 = 0;
  PyObject *vol1_capi = Py_None;
  double vol2 = 0;
  PyObject *vol2_capi = Py_None;
  double vol3 = 0;
  PyObject *vol3_capi = Py_None;
  complex_double m1;
  PyObject *m1_capi = Py_None;
  complex_double m2;
  PyObject *m2_capi = Py_None;
  complex_double m3;
  PyObject *m3_capi = Py_None;
  string inclusion = NULL;
  int slen(inclusion);
  PyObject *inclusion_capi = Py_None;
  int error = 0;
    static char *capi_kwlist[] = {"mmg","vol1","vol2","vol3","m1","m2","m3","inclusion",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|:cmpref.cmpref_mod.mcomplexmaxwellgarnett",\
        capi_kwlist,&mmg_capi,&vol1_capi,&vol2_capi,&vol3_capi,&m1_capi,&m2_capi,&m3_capi,&inclusion_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable mmg */
    f2py_success = complex_double_from_pyobj(&mmg,mmg_capi,"cmpref.cmpref_mod.mcomplexmaxwellgarnett() 1st argument (mmg) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable m1 */
    f2py_success = complex_double_from_pyobj(&m1,m1_capi,"cmpref.cmpref_mod.mcomplexmaxwellgarnett() 5th argument (m1) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable m2 */
    f2py_success = complex_double_from_pyobj(&m2,m2_capi,"cmpref.cmpref_mod.mcomplexmaxwellgarnett() 6th argument (m2) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable m3 */
    f2py_success = complex_double_from_pyobj(&m3,m3_capi,"cmpref.cmpref_mod.mcomplexmaxwellgarnett() 7th argument (m3) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable vol1 */
    f2py_success = double_from_pyobj(&vol1,vol1_capi,"cmpref.cmpref_mod.mcomplexmaxwellgarnett() 2nd argument (vol1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vol2 */
    f2py_success = double_from_pyobj(&vol2,vol2_capi,"cmpref.cmpref_mod.mcomplexmaxwellgarnett() 3rd argument (vol2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vol3 */
    f2py_success = double_from_pyobj(&vol3,vol3_capi,"cmpref.cmpref_mod.mcomplexmaxwellgarnett() 4th argument (vol3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable inclusion */
  slen(inclusion) = -1;
  f2py_success = string_from_pyobj(&inclusion,&slen(inclusion),"",inclusion_capi,"string_from_pyobj failed in converting 8th argument `inclusion' of cmpref.cmpref_mod.mcomplexmaxwellgarnett to C string");
  if (f2py_success) {
  /* Processing variable error */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&mmg,&vol1,&vol2,&vol3,&m1,&m2,&m3,inclusion,&error,slen(inclusion));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",error);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable error */
    STRINGFREE(inclusion);
  }  /*if (f2py_success) of inclusion*/
  /* End of cleaning variable inclusion */
  } /*if (f2py_success) of vol3*/
  /* End of cleaning variable vol3 */
  } /*if (f2py_success) of vol2*/
  /* End of cleaning variable vol2 */
  } /*if (f2py_success) of vol1*/
  /* End of cleaning variable vol1 */
  }  /*if (f2py_success) of m3 frompyobj*/
  /* End of cleaning variable m3 */
  }  /*if (f2py_success) of m2 frompyobj*/
  /* End of cleaning variable m2 */
  }  /*if (f2py_success) of m1 frompyobj*/
  /* End of cleaning variable m1 */
  }  /*if (f2py_success) of mmg frompyobj*/
  /* End of cleaning variable mmg */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********************** end of mcomplexmaxwellgarnett ***********************/

/****************************** make_rainnumber ******************************/
static char doc_f2py_rout_cmpref_cmpref_mod_make_rainnumber[] = "\
rnc = make_rainnumber(Qrain,temp)\n\nWrapper for ``make_rainnumber``.\
\n\nParameters\n----------\n"
"Qrain : input float\n"
"temp : input float\n"
"\nReturns\n-------\n"
"rnc : float";
/*  */
static PyObject *f2py_rout_cmpref_cmpref_mod_make_rainnumber(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float rnc = 0;
  float Qrain = 0;
  PyObject *Qrain_capi = Py_None;
  float temp = 0;
  PyObject *temp_capi = Py_None;
    static char *capi_kwlist[] = {"Qrain","temp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:cmpref.cmpref_mod.make_rainnumber",\
        capi_kwlist,&Qrain_capi,&temp_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable rnc */
  /* Processing variable Qrain */
    f2py_success = float_from_pyobj(&Qrain,Qrain_capi,"cmpref.cmpref_mod.make_rainnumber() 1st argument (Qrain) can't be converted to float");
  if (f2py_success) {
  /* Processing variable temp */
    f2py_success = float_from_pyobj(&temp,temp_capi,"cmpref.cmpref_mod.make_rainnumber() 2nd argument (temp) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&rnc,&Qrain,&temp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",rnc);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  } /*if (f2py_success) of Qrain*/
  /* End of cleaning variable Qrain */
  /* End of cleaning variable rnc */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of make_rainnumber ***************************/

/********************************* radar_init *********************************/
static char doc_f2py_rout_cmpref_share_mod_radar_init[] = "\
radar_init()\n\nWrapper for ``radar_init``.\
\n";
/*  */
static PyObject *f2py_rout_cmpref_share_mod_radar_init(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:cmpref.share_mod.radar_init",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of radar_init *****************************/

/**************************** m_complex_water_ray ****************************/
static char doc_f2py_rout_cmpref_share_mod_m_complex_water_ray[] = "\
m_complex_water_ray(mcwr,lambda,T)\n\nWrapper for ``m_complex_water_ray``.\
\n\nParameters\n----------\n"
"mcwr : input complex\n"
"lambda : input float\n"
"T : input float";
/*  */
static PyObject *f2py_rout_cmpref_share_mod_m_complex_water_ray(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  complex_double mcwr;
  PyObject *mcwr_capi = Py_None;
  double lambda = 0;
  PyObject *lambda_capi = Py_None;
  double T = 0;
  PyObject *T_capi = Py_None;
    static char *capi_kwlist[] = {"mcwr","lambda","T",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:cmpref.share_mod.m_complex_water_ray",\
        capi_kwlist,&mcwr_capi,&lambda_capi,&T_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable mcwr */
    f2py_success = complex_double_from_pyobj(&mcwr,mcwr_capi,"cmpref.share_mod.m_complex_water_ray() 1st argument (mcwr) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable T */
    f2py_success = double_from_pyobj(&T,T_capi,"cmpref.share_mod.m_complex_water_ray() 3rd argument (T) can't be converted to double");
  if (f2py_success) {
  /* Processing variable lambda */
    f2py_success = double_from_pyobj(&lambda,lambda_capi,"cmpref.share_mod.m_complex_water_ray() 2nd argument (lambda) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&mcwr,&lambda,&T);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of lambda*/
  /* End of cleaning variable lambda */
  } /*if (f2py_success) of T*/
  /* End of cleaning variable T */
  }  /*if (f2py_success) of mcwr frompyobj*/
  /* End of cleaning variable mcwr */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************* end of m_complex_water_ray *************************/

/*************************** m_complex_ice_maetzler ***************************/
static char doc_f2py_rout_cmpref_share_mod_m_complex_ice_maetzler[] = "\
m_complex_ice_maetzler(mcim,lambda,T,dummy)\n\nWrapper for ``m_complex_ice_maetzler``.\
\n\nParameters\n----------\n"
"mcim : input complex\n"
"lambda : input float\n"
"T : input float\n"
"dummy : input int";
/*  */
static PyObject *f2py_rout_cmpref_share_mod_m_complex_ice_maetzler(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_double*,double*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  complex_double mcim;
  PyObject *mcim_capi = Py_None;
  double lambda = 0;
  PyObject *lambda_capi = Py_None;
  double T = 0;
  PyObject *T_capi = Py_None;
  int dummy = 0;
  PyObject *dummy_capi = Py_None;
    static char *capi_kwlist[] = {"mcim","lambda","T","dummy",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:cmpref.share_mod.m_complex_ice_maetzler",\
        capi_kwlist,&mcim_capi,&lambda_capi,&T_capi,&dummy_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable mcim */
    f2py_success = complex_double_from_pyobj(&mcim,mcim_capi,"cmpref.share_mod.m_complex_ice_maetzler() 1st argument (mcim) can't be converted to complex_double");
  if (f2py_success) {
  /* Processing variable T */
    f2py_success = double_from_pyobj(&T,T_capi,"cmpref.share_mod.m_complex_ice_maetzler() 3rd argument (T) can't be converted to double");
  if (f2py_success) {
  /* Processing variable lambda */
    f2py_success = double_from_pyobj(&lambda,lambda_capi,"cmpref.share_mod.m_complex_ice_maetzler() 2nd argument (lambda) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dummy */
    f2py_success = int_from_pyobj(&dummy,dummy_capi,"cmpref.share_mod.m_complex_ice_maetzler() 4th argument (dummy) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&mcim,&lambda,&T,&dummy);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of dummy*/
  /* End of cleaning variable dummy */
  } /*if (f2py_success) of lambda*/
  /* End of cleaning variable lambda */
  } /*if (f2py_success) of T*/
  /* End of cleaning variable T */
  }  /*if (f2py_success) of mcim frompyobj*/
  /* End of cleaning variable mcim */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********************** end of m_complex_ice_maetzler ***********************/

/*********************************** wgamma ***********************************/
static char doc_f2py_rout_cmpref_share_mod_wgamma[] = "\
wgamma(gln,XX)\n\nWrapper for ``wgamma``.\
\n\nParameters\n----------\n"
"gln : input float\n"
"XX : input float";
/*  */
static PyObject *f2py_rout_cmpref_share_mod_wgamma(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float gln = 0;
  PyObject *gln_capi = Py_None;
  float XX = 0;
  PyObject *XX_capi = Py_None;
    static char *capi_kwlist[] = {"gln","XX",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:cmpref.share_mod.wgamma",\
        capi_kwlist,&gln_capi,&XX_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable gln */
    f2py_success = float_from_pyobj(&gln,gln_capi,"cmpref.share_mod.wgamma() 1st argument (gln) can't be converted to float");
  if (f2py_success) {
  /* Processing variable XX */
    f2py_success = float_from_pyobj(&XX,XX_capi,"cmpref.share_mod.wgamma() 2nd argument (XX) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&gln,&XX);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of XX*/
  /* End of cleaning variable XX */
  } /*if (f2py_success) of gln*/
  /* End of cleaning variable gln */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of wgamma *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_cmpref_mod_def[] = {
  {"calcrefl10cm",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_cmpref_mod_calcrefl10cm,doc_f2py_rout_cmpref_cmpref_mod_calcrefl10cm},
  {"calcrefl10cm1d",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_cmpref_mod_calcrefl10cm1d,doc_f2py_rout_cmpref_cmpref_mod_calcrefl10cm1d},
  {"rayleighsoakwetgraupel",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_cmpref_mod_rayleighsoakwetgraupel,doc_f2py_rout_cmpref_cmpref_mod_rayleighsoakwetgraupel},
  {"get_m_mix_nested",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_cmpref_mod_get_m_mix_nested,doc_f2py_rout_cmpref_cmpref_mod_get_m_mix_nested},
  {"get_m_mix",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_cmpref_mod_get_m_mix,doc_f2py_rout_cmpref_cmpref_mod_get_m_mix},
  {"mcomplexmaxwellgarnett",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_cmpref_mod_mcomplexmaxwellgarnett,doc_f2py_rout_cmpref_cmpref_mod_mcomplexmaxwellgarnett},
  {"make_rainnumber",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_cmpref_mod_make_rainnumber,doc_f2py_rout_cmpref_cmpref_mod_make_rainnumber},
  {NULL}
};

static void f2py_setup_cmpref_mod(char *calcrefl10cm,char *calcrefl10cm1d,char *rayleighsoakwetgraupel,char *get_m_mix_nested,char *get_m_mix,char *mcomplexmaxwellgarnett,char *make_rainnumber) {
  int i_f2py=0;
  f2py_cmpref_mod_def[i_f2py++].data = calcrefl10cm;
  f2py_cmpref_mod_def[i_f2py++].data = calcrefl10cm1d;
  f2py_cmpref_mod_def[i_f2py++].data = rayleighsoakwetgraupel;
  f2py_cmpref_mod_def[i_f2py++].data = get_m_mix_nested;
  f2py_cmpref_mod_def[i_f2py++].data = get_m_mix;
  f2py_cmpref_mod_def[i_f2py++].data = mcomplexmaxwellgarnett;
  f2py_cmpref_mod_def[i_f2py++].data = make_rainnumber;
}
extern void F_FUNC_US(f2pyinitcmpref_mod,F2PYINITCMPREF_MOD)(void (*)(char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_cmpref_mod(void) {
  F_FUNC_US(f2pyinitcmpref_mod,F2PYINITCMPREF_MOD)(f2py_setup_cmpref_mod);
}


static FortranDataDef f2py_share_mod_def[] = {
  {"nrbins",0,{{-1}},NPY_INT},
  {"xxDx",1,{{51}},NPY_DOUBLE},
  {"xxDs",1,{{50}},NPY_DOUBLE},
  {"xdts",1,{{50}},NPY_DOUBLE},
  {"xxDg",1,{{50}},NPY_DOUBLE},
  {"xdtg",1,{{50}},NPY_DOUBLE},
  {"lamdaradar",0,{{-1}},NPY_DOUBLE},
  {"Kw",0,{{-1}},NPY_DOUBLE},
  {"PI5",0,{{-1}},NPY_DOUBLE},
  {"lamda4",0,{{-1}},NPY_DOUBLE},
  {"mw0",0,{{-1}},NPY_CDOUBLE},
  {"mi0",0,{{-1}},NPY_CDOUBLE},
  {"simpson",1,{{51}},NPY_DOUBLE},
  {"basis",1,{{3}},NPY_DOUBLE},
  {"xcre",1,{{4}},NPY_FLOAT},
  {"xcse",1,{{4}},NPY_FLOAT},
  {"xcge",1,{{4}},NPY_FLOAT},
  {"xcrg",1,{{4}},NPY_FLOAT},
  {"xcsg",1,{{4}},NPY_FLOAT},
  {"xcgg",1,{{4}},NPY_FLOAT},
  {"xamr",0,{{-1}},NPY_FLOAT},
  {"xbmr",0,{{-1}},NPY_FLOAT},
  {"xmur",0,{{-1}},NPY_FLOAT},
  {"xobmr",0,{{-1}},NPY_FLOAT},
  {"xams",0,{{-1}},NPY_FLOAT},
  {"xbms",0,{{-1}},NPY_FLOAT},
  {"xmus",0,{{-1}},NPY_FLOAT},
  {"xoams",0,{{-1}},NPY_FLOAT},
  {"xobms",0,{{-1}},NPY_FLOAT},
  {"xocms",0,{{-1}},NPY_FLOAT},
  {"xamg",0,{{-1}},NPY_FLOAT},
  {"xbmg",0,{{-1}},NPY_FLOAT},
  {"xmug",0,{{-1}},NPY_FLOAT},
  {"xoamg",0,{{-1}},NPY_FLOAT},
  {"xobmg",0,{{-1}},NPY_FLOAT},
  {"xocmg",0,{{-1}},NPY_FLOAT},
  {"xorg2",0,{{-1}},NPY_FLOAT},
  {"xosg2",0,{{-1}},NPY_FLOAT},
  {"xogg2",0,{{-1}},NPY_FLOAT},
  {"PI",0,{{-1}},NPY_FLOAT},
  {"slen",0,{{-1}},NPY_INT},
  {"mixingrulestrings",1,{{20}},NPY_STRING},
  {"matrixstrings",1,{{20}},NPY_STRING},
  {"inclusionstrings",1,{{20}},NPY_STRING},
  {"hoststrings",1,{{20}},NPY_STRING},
  {"hostmatrixstrings",1,{{20}},NPY_STRING},
  {"hostinclusionstrings",1,{{20}},NPY_STRING},
  {"mixingrulestringg",1,{{20}},NPY_STRING},
  {"matrixstringg",1,{{20}},NPY_STRING},
  {"inclusionstringg",1,{{20}},NPY_STRING},
  {"hoststringg",1,{{20}},NPY_STRING},
  {"hostmatrixstringg",1,{{20}},NPY_STRING},
  {"hostinclusionstringg",1,{{20}},NPY_STRING},
  {"meltoutsides",0,{{-1}},NPY_DOUBLE},
  {"meltoutsideg",0,{{-1}},NPY_DOUBLE},
  {"radar_init",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_share_mod_radar_init,doc_f2py_rout_cmpref_share_mod_radar_init},
  {"m_complex_water_ray",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_share_mod_m_complex_water_ray,doc_f2py_rout_cmpref_share_mod_m_complex_water_ray},
  {"m_complex_ice_maetzler",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_share_mod_m_complex_ice_maetzler,doc_f2py_rout_cmpref_share_mod_m_complex_ice_maetzler},
  {"wgamma",-1,{{-1}},0,NULL,(void *)f2py_rout_cmpref_share_mod_wgamma,doc_f2py_rout_cmpref_share_mod_wgamma},
  {NULL}
};

static void f2py_setup_share_mod(char *nrbins,char *xxDx,char *xxDs,char *xdts,char *xxDg,char *xdtg,char *lamdaradar,char *Kw,char *PI5,char *lamda4,char *mw0,char *mi0,char *simpson,char *basis,char *xcre,char *xcse,char *xcge,char *xcrg,char *xcsg,char *xcgg,char *xamr,char *xbmr,char *xmur,char *xobmr,char *xams,char *xbms,char *xmus,char *xoams,char *xobms,char *xocms,char *xamg,char *xbmg,char *xmug,char *xoamg,char *xobmg,char *xocmg,char *xorg2,char *xosg2,char *xogg2,char *PI,char *slen_bn,char *mixingrulestrings,char *matrixstrings,char *inclusionstrings,char *hoststrings,char *hostmatrixstrings,char *hostinclusionstrings,char *mixingrulestringg,char *matrixstringg,char *inclusionstringg,char *hoststringg,char *hostmatrixstringg,char *hostinclusionstringg,char *meltoutsides,char *meltoutsideg,char *radar_init,char *m_complex_water_ray,char *m_complex_ice_maetzler,char *wgamma) {
  int i_f2py=0;
  f2py_share_mod_def[i_f2py++].data = nrbins;
  f2py_share_mod_def[i_f2py++].data = xxDx;
  f2py_share_mod_def[i_f2py++].data = xxDs;
  f2py_share_mod_def[i_f2py++].data = xdts;
  f2py_share_mod_def[i_f2py++].data = xxDg;
  f2py_share_mod_def[i_f2py++].data = xdtg;
  f2py_share_mod_def[i_f2py++].data = lamdaradar;
  f2py_share_mod_def[i_f2py++].data = Kw;
  f2py_share_mod_def[i_f2py++].data = PI5;
  f2py_share_mod_def[i_f2py++].data = lamda4;
  f2py_share_mod_def[i_f2py++].data = mw0;
  f2py_share_mod_def[i_f2py++].data = mi0;
  f2py_share_mod_def[i_f2py++].data = simpson;
  f2py_share_mod_def[i_f2py++].data = basis;
  f2py_share_mod_def[i_f2py++].data = xcre;
  f2py_share_mod_def[i_f2py++].data = xcse;
  f2py_share_mod_def[i_f2py++].data = xcge;
  f2py_share_mod_def[i_f2py++].data = xcrg;
  f2py_share_mod_def[i_f2py++].data = xcsg;
  f2py_share_mod_def[i_f2py++].data = xcgg;
  f2py_share_mod_def[i_f2py++].data = xamr;
  f2py_share_mod_def[i_f2py++].data = xbmr;
  f2py_share_mod_def[i_f2py++].data = xmur;
  f2py_share_mod_def[i_f2py++].data = xobmr;
  f2py_share_mod_def[i_f2py++].data = xams;
  f2py_share_mod_def[i_f2py++].data = xbms;
  f2py_share_mod_def[i_f2py++].data = xmus;
  f2py_share_mod_def[i_f2py++].data = xoams;
  f2py_share_mod_def[i_f2py++].data = xobms;
  f2py_share_mod_def[i_f2py++].data = xocms;
  f2py_share_mod_def[i_f2py++].data = xamg;
  f2py_share_mod_def[i_f2py++].data = xbmg;
  f2py_share_mod_def[i_f2py++].data = xmug;
  f2py_share_mod_def[i_f2py++].data = xoamg;
  f2py_share_mod_def[i_f2py++].data = xobmg;
  f2py_share_mod_def[i_f2py++].data = xocmg;
  f2py_share_mod_def[i_f2py++].data = xorg2;
  f2py_share_mod_def[i_f2py++].data = xosg2;
  f2py_share_mod_def[i_f2py++].data = xogg2;
  f2py_share_mod_def[i_f2py++].data = PI;
  f2py_share_mod_def[i_f2py++].data = slen_bn;
  f2py_share_mod_def[i_f2py++].data = mixingrulestrings;
  f2py_share_mod_def[i_f2py++].data = matrixstrings;
  f2py_share_mod_def[i_f2py++].data = inclusionstrings;
  f2py_share_mod_def[i_f2py++].data = hoststrings;
  f2py_share_mod_def[i_f2py++].data = hostmatrixstrings;
  f2py_share_mod_def[i_f2py++].data = hostinclusionstrings;
  f2py_share_mod_def[i_f2py++].data = mixingrulestringg;
  f2py_share_mod_def[i_f2py++].data = matrixstringg;
  f2py_share_mod_def[i_f2py++].data = inclusionstringg;
  f2py_share_mod_def[i_f2py++].data = hoststringg;
  f2py_share_mod_def[i_f2py++].data = hostmatrixstringg;
  f2py_share_mod_def[i_f2py++].data = hostinclusionstringg;
  f2py_share_mod_def[i_f2py++].data = meltoutsides;
  f2py_share_mod_def[i_f2py++].data = meltoutsideg;
  f2py_share_mod_def[i_f2py++].data = radar_init;
  f2py_share_mod_def[i_f2py++].data = m_complex_water_ray;
  f2py_share_mod_def[i_f2py++].data = m_complex_ice_maetzler;
  f2py_share_mod_def[i_f2py++].data = wgamma;
}
extern void F_FUNC_US(f2pyinitshare_mod,F2PYINITSHARE_MOD)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char *,char *,char *,char *));
static void f2py_init_share_mod(void) {
  F_FUNC_US(f2pyinitshare_mod,F2PYINITSHARE_MOD)(f2py_setup_share_mod);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "cmpref",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_cmpref(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = cmpref_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module cmpref (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyUnicode_FromString("1.21.5");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'cmpref' is auto-generated with f2py (version:1.21.5).\nFunctions:\n"
"Fortran 90/95 modules:\n""  cmpref_mod --- calcrefl10cm(),calcrefl10cm1d(),rayleighsoakwetgraupel(),get_m_mix_nested(),get_m_mix(),mcomplexmaxwellgarnett(),make_rainnumber()""  share_mod --- nrbins,xxDx,xxDs,xdts,xxDg,xdtg,lamdaradar,Kw,PI5,lamda4,mw0,mi0,simpson,basis,xcre,xcse,xcge,xcrg,xcsg,xcgg,xamr,xbmr,xmur,xobmr,xams,xbms,xmus,xoams,xobms,xocms,xamg,xbmg,xmug,xoamg,xobmg,xocmg,xorg2,xosg2,xogg2,PI,slen,mixingrulestrings,matrixstrings,inclusionstrings,hoststrings,hostmatrixstrings,hostinclusionstrings,mixingrulestringg,matrixstringg,inclusionstringg,hoststringg,hostmatrixstringg,hostinclusionstringg,meltoutsides,meltoutsideg,radar_init(),m_complex_water_ray(),m_complex_ice_maetzler(),wgamma()"".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString("1.21.5");
  PyDict_SetItemString(d, "__f2py_numpy_version__", s);
  Py_DECREF(s);
  cmpref_error = PyErr_NewException ("cmpref.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_cmpref_error", cmpref_error);
  Py_DECREF(cmpref_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }











/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "share_mod", PyFortranObject_New(f2py_share_mod_def,f2py_init_share_mod));
  PyDict_SetItemString(d, "cmpref_mod", PyFortranObject_New(f2py_cmpref_mod_def,f2py_init_cmpref_mod));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"cmpref");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
